add skip cutscene key shorcut
KadeArchive/Kade-Engine pull request #1539
Opened 2021-08-01 18:08 UTC by napstaa967

saw what kade said on my last pr so i turned the option into a key shorcut

if you enable the skip button on gameplay options and press escape/backspace you can skip cutscenes

2021-08-01 18:12 UTC, napstaa967 commented
i am trying to test in thorns but the game crashes as soon as i load in the song

2021-08-02 11:59 UTC, Lucky-56 commented
then mark this as a draft

2021-08-05 21:22 UTC, napstaa967 commented
ok now that funny spirit is fixed i have to test it

2021-08-06 04:48 UTC, napstaa967 commented
i can't get thorns to work it ignores all inputs

2021-08-11 08:33 UTC, brosomethingwrongwithyothing approved these changes
looks good to go

2021-08-13 10:24 UTC, Lucky-56 requested changes
you forgot to set a default boolean in `KadeEngineData.hx`, else it looks good.

2021-08-15 05:31 UTC, napstaa967 commented
> you forgot to set a default value for `cutscenes` in `KadeEngineData.hx`, else it looks good.

i forgot

2021-08-15 11:00 UTC, Lucky-56 requested changes

2021-08-15 11:00 UTC, Lucky-56 commented on source/KadeEngineData.hx
> +			FlxG.save.data.downscroll = false;
heh, I hope you see what's wrong...
if not, `FlxG.save.data.downscroll` should be `FlxG.save.data.cutscenes`.

2021-08-15 18:58 UTC, Lucky-56 approved these changes
looks good

2021-09-05 21:03 UTC, KadeDev commented
Again I generally just don't want this to be an option. it would clutter shit up.

2021-09-05 21:03 UTC, closed without merging