Added health, setHealth, changeDadCharacter, changeBoyfriendCharacter, keyPressed to modcharting
KadeArchive/Kade-Engine pull request #582
Opened 2021-05-25 20:24 UTC by craftersshaft

messy implementation but just a quick project i whipped up from learning the source code. added most of the documentation to the docs but forgot to mention changeDadCharacter and changeBoyfriendCharacter, but those work by just taking a character name as an argument (for example, "pico" or "senpai".) 

Example of keyPressed:
`function keyPressed(key)
	if key == "left" then
	setActorX(getActorX("boyfriend")-10, "boyfriend")
	changeDadCharacter("pico")
	end
	if key == "right" then
	setActorX(getActorX("boyfriend")+10, "boyfriend")
	end
	if key == "up" then
	setActorY(getActorY("boyfriend")-10, "boyfriend")
	end
	if key == "down" then
	setActorY(getActorY("boyfriend")+10, "boyfriend")
	end	
end`

first time doing a pull request so if i need to do anything else let me know

2021-05-25 21:55 UTC, prokube approved these changes
yo ho ho, pretty good

2021-05-26 07:29 UTC, daniel11420 requested changes, later dismissed
`source/PlayState.hx:1836: characters 27-38 : Unknown identifier : luaModchart`

2021-05-26 11:03 UTC, craftersshaft commented
whoops, guess i forgot the #if windows part again

2021-05-27 08:57 UTC, KadeDev requested changes
health shouldn't be added

2021-05-27 08:57 UTC, KadeDev commented on source/ModchartState.hx
> +				setVar("health", PlayState.instance.health);
No point in having this since getProperty(); exists, soon with setProperty(); as well

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +			if (executeModchart && luaModchart != null){luaModchart.setVar('health', health);};
same with this one

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +							if (executeModchart && luaModchart != null){	luaModchart.setVar('health', health);};
same with this one

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +					if (executeModchart && luaModchart != null){	luaModchart.setVar('health', health);};
same with this one

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +					if (executeModchart && luaModchart != null){	luaModchart.setVar('health', health);};
same with this one

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +						if (executeModchart && luaModchart != null){	luaModchart.setVar('health', health);};
same with this one

2021-05-27 08:57 UTC, KadeDev commented on source/PlayState.hx
> +						if (executeModchart && luaModchart != null){	luaModchart.setVar('health', health);};
same with this one

2021-05-27 18:25 UTC, KadeDev commented
Looks good now.

2021-05-27 18:25 UTC, KadeDev approved these changes

2021-05-27 18:26 UTC, craftersshaft commented
thanks for letting me know, removed health variables but kept the others in for now, also forgot to update the modchart to add the extra functions and remove health

2021-05-27 18:26 UTC, merged

2021-05-27 18:27 UTC, craftersshaft commented
just realized i forgot to remove setHealth, but that'll probably be gone once setProperty exists