compatibility changes for dadbattle + philly
KadeArchive/Kade-Engine pull request #789
Opened 2021-06-08 05:19 UTC by Lucky-56

fixes:

- 'Dad Battle' now has compatibility again *yay*

'Dad Battle' is now called 'Dad Battle' in game and uses 'dadbattle' as files
'Philly' is now called 'Philly Nice' in game and uses 'philly' as files

2021-06-08 05:46 UTC, Lucky-56 commented
@theDetourist here ya go

2021-06-08 10:52 UTC, puyoxyz requested changes

2021-06-08 10:52 UTC, puyoxyz commented on source/FreeplayState.hx
> +			var songLowercase = switch (songs[curSelected].songName)
This switch case is hella wack you're repeating code and changing like one argument

Do something like this instead

```haxe
var songLowercase = StringTools.replace(PlayState.SONG.song, " ", "-").toLowerCase();
switch (songLowercase) {
  case 'dad-battle': songLowercase = 'dadbattle';
  case 'philly-nice': songLowercase = 'philly';
}
```

2021-06-08 10:52 UTC, puyoxyz commented on source/Paths.hx
> +		var songLowercase = switch (song)
See previous

2021-06-08 10:52 UTC, daniel11420 commented on source/Paths.hx
> +		var songLowercase = switch (song)
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/PlayState.hx
> +		// pre lowercasing the song name (create)
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/PlayState.hx
> +		// pre lowercasing the song name (schoolIntro)
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/PlayState.hx
> +		var songLowercase = switch (PlayState.SONG.song)
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/PlayState.hx
> +					// pre lowercasing the next story song name
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/PlayState.hx
> +					var songLowercase = switch (PlayState.SONG.song)
see previous

2021-06-08 10:52 UTC, daniel11420 commented on source/Song.hx
> +		var folderLowercase = switch (folder)
see previous

2021-06-08 10:55 UTC, Lucky-56 commented
sure, changes comin' right up

2021-06-08 12:14 UTC, puyoxyz approved these changes
Looks good; @Lucky-56 did you test it with the new changes?

2021-06-08 12:42 UTC, Lucky-56 commented
ok... wierd things are happening.
I start Philly in freeplay, but I play Satin Panties... ?

2021-06-08 12:45 UTC, Lucky-56 commented
ah ok I broke Freeplay, nothing I can't fix

2021-06-08 14:28 UTC, Lucky-56 commented
it just crashes when going into freeplay now.. and I'm too tired to it now :/

2021-06-09 03:07 UTC, Lucky-56 commented
it works now tested it completely

2021-06-09 10:29 UTC, daniel11420 approved these changes
Yep

2021-06-09 10:29 UTC, daniel11420 commented on source/FreeplayState.hx
> +			}
there *has to* be a less janky way to do this but this whole codebase is wack so whatever

2021-06-09 13:18 UTC, Lucky-56 commented
just checked and remembered
1. it doesn't even get called at the beginning of the song
2. it's only a problem on my mod  😅

2021-06-09 16:48 UTC, prokube approved these changes
imagine making a commit and then immediately reverting it LOLL

2021-06-09 17:02 UTC, Lucky-56 commented
yeah because I noticed it right when I commited... heh

2021-06-09 18:37 UTC, Lucky-56 commented
Fixes #779 
#790 don't know yet would assume it fixes that
Fixes #796 
Fixes #804 
Fixes #805  
i guess

2021-06-10 03:43 UTC, ActualMandM requested changes
Winter Horrorland also needs the compatibility changes.

2021-06-10 03:45 UTC, ActualMandM approved these changes
nvm, disregard what i said

2021-06-10 19:36 UTC, daniel11420 commented
@KadeDev ??????????????????

2021-06-10 19:56 UTC, merged

2021-06-10 19:56 UTC, KadeDev commented
sorryy!!!

2021-06-11 08:41 UTC, Lucky-56 commented
yeah it's only hardcoded because it's for compatibility