weeks are now based on txt files
KadeArchive/Kade-Engine pull request #895
Opened 2021-06-17 16:12 UTC by Lucky-56

Puyo said it wouldn't be needed, but if you want to merge that's on you. 😉

2021-06-18 00:39 UTC, ACardboardBox1 commented
soon the whole game will be txt files

2021-06-18 00:51 UTC, puyoxyz requested changes
why are you separating them into THREE DIFFERENT FILES

2021-06-19 06:01 UTC, puyoxyz requested changes

2021-06-19 06:01 UTC, puyoxyz commented on source/StoryMenuState.hx
> +				var dataTwo:Array<String> = data[i].split(', ');
don't force the space after `;`/`,`. instead, do `split(',')`/`split(';')` then [trim()](https://api.haxe.org/StringTools.html#trim) it

2021-06-19 06:19 UTC, Lucky-56 commented on source/StoryMenuState.hx
> +				var dataTwo:Array<String> = data[i].split(', ');
okay

2021-06-19 07:00 UTC, puyoxyz reviewed
seems cool but needs to be tested (cant myself kinda busy with stuff right now;; if noone tests and reviews in like a day or two request my review again)

2021-06-19 09:26 UTC, Lucky-56 commented
hey @puyoxyz, fun fact this fixes my problem I'm having with [patch-3](https://github.com/KadeDev/Kade-Engine/pull/894#discussion_r654770492),
so not really useless, but I'm sure there's another way to fix my issue on [patch-3](https://github.com/KadeDev/Kade-Engine/pull/894#discussion_r654770492)

2021-06-20 07:00 UTC, Lucky-56 commented
how about I change it that instead of it being a txt file this just puts all of the week data into one array ?

2021-06-20 07:52 UTC, Lucky-56 commented
nvm, I just noticed that I hate this
## Pick it up if you really want to (but I doubt)

2021-06-20 07:52 UTC, closed without merging